
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lraaziwkviznwzhbiief.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyYWF6aXdrdml6bnd6aGJpaWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjkwNDAsImV4cCI6MjA2MTgwNTA0MH0.0VwED9hQXXq0OqR1T33XImWjYw4kOK8isEpLKtOG018";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
    },
    global: {
      fetch: (url: RequestInfo | URL, init?: RequestInit) => fetch(url, init),
    },
  }
);
